name: mongo_dart_query
version: 0.4.0
authors:
  - Vadim Tsushko <vadimtsushko@gmail.com>
  - Joel Trottier-Hebert <iamquebecois@gmail.com>
  - Alexey Danilevsky <alexey.danilevsky@gmail.com>
description: Query builder for mongo_dart and objectory
homepage: https://github.com/mongo-dart/mongo_dart_query
environment:
  sdk: ">=2.0.0-dev.69.0 <3.0.0"
dependencies:
  bson: "^0.3.2"
  meta: ^1.1.7
dev_dependencies:
  test: "^1.3.0"
  #dart_coveralls: ">=0.4.0"
